// apps/api/src/database/seeds/complaints.seed.ts
/**
 * Seed data for complaint workflow testing.
 * Usage: imported by seed.ts runner.
 * Each complaint represents a different stage of the OPEN → CLOSED lifecycle.
 */
import { v4 as uuid } from 'uuid';
import { ComplaintStatus, ComplaintCategory, WorkOrderStatus } from '@ax/shared';

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000).toISOString();

export function buildComplaintSeeds(orgId: string, complexId: string, userId: string) {
  const complaints = [
    // 1. 긴급 — 누수 (OPEN, URGENT, 기한 초과)
    {
      _id: `complaint:${orgId}:cmp_seed_001`,
      docType: 'complaint',
      orgId,
      complexId,
      buildingId: 'B001',
      unitNumber: '203호',
      category: ComplaintCategory.FACILITY,
      title: '3층 화장실 배관 누수',
      description: '3층 화장실 천장에서 물이 새고 있습니다. 2층까지 영향이 있으며 긴급 수리가 필요합니다.',
      status: ComplaintStatus.ASSIGNED,
      priority: 'URGENT',
      submittedBy: '김입주민',
      submittedPhone: '010-1234-5678',
      submittedAt: daysAgo(3),
      assignedTo: `user:${orgId}:inspector001`,
      assignedAt: daysAgo(2),
      dueDate: daysAgo(1),   // 기한 초과
      mediaIds: [],
      classificationHint: '누수',
      timeline: [
        { timestamp: daysAgo(3), fromStatus: null, toStatus: ComplaintStatus.OPEN, actorId: userId, notes: '민원 접수' },
        { timestamp: daysAgo(2), fromStatus: ComplaintStatus.OPEN, toStatus: ComplaintStatus.TRIAGED, actorId: userId, notes: '긴급 분류 완료' },
        { timestamp: daysAgo(2), fromStatus: ComplaintStatus.TRIAGED, toStatus: ComplaintStatus.ASSIGNED, actorId: userId, notes: `담당자 배정: inspector001` },
      ],
      createdAt: daysAgo(3),
      updatedAt: daysAgo(2),
      createdBy: userId,
      updatedBy: userId,
    },

    // 2. 균열 (IN_PROGRESS)
    {
      _id: `complaint:${orgId}:cmp_seed_002`,
      docType: 'complaint',
      orgId,
      complexId,
      buildingId: 'B001',
      unitNumber: null,
      category: ComplaintCategory.SAFETY,
      title: '외벽 균열 발견 (101동 3층)',
      description: '101동 3층 외벽에 큰 균열이 있습니다. 콘크리트 조각이 떨어질 위험이 있어 안전 조치가 필요합니다.',
      status: ComplaintStatus.IN_PROGRESS,
      priority: 'HIGH',
      submittedBy: '이주민',
      submittedAt: daysAgo(5),
      assignedTo: `user:${orgId}:inspector001`,
      assignedAt: daysAgo(4),
      dueDate: daysAgo(-2), // 이틀 후 기한
      mediaIds: [],
      classificationHint: '균열',
      timeline: [
        { timestamp: daysAgo(5), fromStatus: null, toStatus: ComplaintStatus.OPEN, actorId: userId, notes: '민원 접수' },
        { timestamp: daysAgo(4), fromStatus: ComplaintStatus.OPEN, toStatus: ComplaintStatus.TRIAGED, actorId: userId, notes: '안전 관련 우선 처리' },
        { timestamp: daysAgo(4), fromStatus: ComplaintStatus.TRIAGED, toStatus: ComplaintStatus.ASSIGNED, actorId: userId, notes: '담당자 배정' },
        { timestamp: daysAgo(3), fromStatus: ComplaintStatus.ASSIGNED, toStatus: ComplaintStatus.IN_PROGRESS, actorId: `user:${orgId}:inspector001`, notes: '현장 점검 시작' },
      ],
      createdAt: daysAgo(5),
      updatedAt: daysAgo(3),
      createdBy: userId,
      updatedBy: `user:${orgId}:inspector001`,
    },

    // 3. 소음 (OPEN, 미배정)
    {
      _id: `complaint:${orgId}:cmp_seed_003`,
      docType: 'complaint',
      orgId,
      complexId,
      buildingId: 'B002',
      unitNumber: '501호',
      category: ComplaintCategory.NOISE,
      title: '층간 소음 심각 (새벽 시간대)',
      description: '윗집에서 새벽 2-3시 사이에 심한 소음이 발생합니다. 뛰어다니는 소리와 가구 끄는 소리입니다.',
      status: ComplaintStatus.OPEN,
      priority: 'MEDIUM',
      submittedBy: '박입주',
      submittedPhone: '010-9876-5432',
      submittedAt: daysAgo(1),
      dueDate: daysAgo(-7),
      mediaIds: [],
      classificationHint: '소음',
      timeline: [
        { timestamp: daysAgo(1), fromStatus: null, toStatus: ComplaintStatus.OPEN, actorId: userId, notes: '민원 접수' },
      ],
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
      createdBy: userId,
      updatedBy: userId,
    },

    // 4. 공용부 파손 (TRIAGED)
    {
      _id: `complaint:${orgId}:cmp_seed_004`,
      docType: 'complaint',
      orgId,
      complexId,
      buildingId: null,
      category: ComplaintCategory.FACILITY,
      title: '지하 주차장 조명 불량 (A구역)',
      description: '지하 주차장 A구역 조명 5개 중 3개가 소등 상태입니다. 야간 안전 위험이 있습니다.',
      status: ComplaintStatus.TRIAGED,
      priority: 'HIGH',
      submittedBy: '최관리',
      submittedAt: daysAgo(2),
      dueDate: daysAgo(-3),
      mediaIds: [],
      classificationHint: '공용부 파손',
      aiSuggestion: '전기 설비 점검 필요 — 공용부 조명 교체 작업지시 권장',
      timeline: [
        { timestamp: daysAgo(2), fromStatus: null, toStatus: ComplaintStatus.OPEN, actorId: userId, notes: '민원 접수' },
        { timestamp: daysAgo(1), fromStatus: ComplaintStatus.OPEN, toStatus: ComplaintStatus.TRIAGED, actorId: userId, notes: '우선순위 HIGH 분류, 전기 전문업체 필요' },
      ],
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
      createdBy: userId,
      updatedBy: userId,
    },

    // 5. 완료된 민원 (RESOLVED)
    {
      _id: `complaint:${orgId}:cmp_seed_005`,
      docType: 'complaint',
      orgId,
      complexId,
      buildingId: 'B001',
      unitNumber: '102호',
      category: ComplaintCategory.FACILITY,
      title: '현관문 잠금장치 고장',
      description: '현관 도어록 배터리 교체 후에도 인식이 되지 않습니다.',
      status: ComplaintStatus.RESOLVED,
      priority: 'MEDIUM',
      submittedBy: '정입주',
      submittedAt: daysAgo(10),
      assignedTo: `user:${orgId}:inspector001`,
      assignedAt: daysAgo(9),
      resolvedAt: daysAgo(7),
      dueDate: daysAgo(8),
      resolutionNotes: '도어록 교체 완료. 제품: Samsung SHS-2920. 30분 소요.',
      mediaIds: [],
      classificationHint: '시설물',
      timeline: [
        { timestamp: daysAgo(10), fromStatus: null, toStatus: ComplaintStatus.OPEN, actorId: userId, notes: '민원 접수' },
        { timestamp: daysAgo(9), fromStatus: ComplaintStatus.OPEN, toStatus: ComplaintStatus.TRIAGED, actorId: userId, notes: '분류 완료' },
        { timestamp: daysAgo(9), fromStatus: ComplaintStatus.TRIAGED, toStatus: ComplaintStatus.ASSIGNED, actorId: userId, notes: '담당자 배정' },
        { timestamp: daysAgo(8), fromStatus: ComplaintStatus.ASSIGNED, toStatus: ComplaintStatus.IN_PROGRESS, actorId: `user:${orgId}:inspector001`, notes: '현장 방문' },
        { timestamp: daysAgo(7), fromStatus: ComplaintStatus.IN_PROGRESS, toStatus: ComplaintStatus.RESOLVED, actorId: `user:${orgId}:inspector001`, notes: '도어록 교체 완료' },
      ],
      createdAt: daysAgo(10),
      updatedAt: daysAgo(7),
      createdBy: userId,
      updatedBy: `user:${orgId}:inspector001`,
    },

    // 6. 종결 민원 with 만족도 (CLOSED)
    {
      _id: `complaint:${orgId}:cmp_seed_006`,
      docType: 'complaint',
      orgId,
      complexId,
      buildingId: 'B002',
      unitNumber: '301호',
      category: ComplaintCategory.ELEVATOR,
      title: '엘리베이터 오작동 (2호기)',
      description: '2호기 엘리베이터가 3층에서 문이 열리지 않는 현상이 발생합니다.',
      status: ComplaintStatus.CLOSED,
      priority: 'HIGH',
      submittedBy: '강입주',
      submittedAt: daysAgo(20),
      assignedTo: `user:${orgId}:inspector001`,
      assignedAt: daysAgo(19),
      resolvedAt: daysAgo(17),
      closedAt: daysAgo(15),
      dueDate: daysAgo(18),
      resolutionNotes: '엘리베이터 안전 센서 교체 및 정비 완료. 제조사 기사 호출하여 조치.',
      satisfactionScore: 5,
      satisfactionFeedback: '빠른 처리 감사합니다. 이제 정상 작동합니다.',
      mediaIds: [],
      classificationHint: '엘리베이터',
      timeline: [
        { timestamp: daysAgo(20), fromStatus: null, toStatus: ComplaintStatus.OPEN, actorId: userId, notes: '민원 접수' },
        { timestamp: daysAgo(19), fromStatus: ComplaintStatus.OPEN, toStatus: ComplaintStatus.TRIAGED, actorId: userId, notes: '긴급 분류' },
        { timestamp: daysAgo(19), fromStatus: ComplaintStatus.TRIAGED, toStatus: ComplaintStatus.ASSIGNED, actorId: userId, notes: '담당자 배정' },
        { timestamp: daysAgo(18), fromStatus: ComplaintStatus.ASSIGNED, toStatus: ComplaintStatus.IN_PROGRESS, actorId: `user:${orgId}:inspector001`, notes: '엘리베이터 점검 시작' },
        { timestamp: daysAgo(17), fromStatus: ComplaintStatus.IN_PROGRESS, toStatus: ComplaintStatus.RESOLVED, actorId: `user:${orgId}:inspector001`, notes: '정비 완료' },
        { timestamp: daysAgo(15), fromStatus: ComplaintStatus.RESOLVED, toStatus: ComplaintStatus.CLOSED, actorId: userId, notes: '입주민 확인 완료 → 종결' },
      ],
      createdAt: daysAgo(20),
      updatedAt: daysAgo(15),
      createdBy: userId,
      updatedBy: userId,
    },
  ];

  const workOrders = [
    {
      _id: `workOrder:${orgId}:wo_seed_001`,
      docType: 'workOrder',
      orgId,
      complexId,
      buildingId: 'B001',
      complaintId: `complaint:${orgId}:cmp_seed_002`,
      title: '101동 3층 외벽 균열 긴급 점검 및 보수',
      description: '균열 범위 측정 후 에폭시 주입 보수 시공. 위험 구역 안전 테이프 설치.',
      assignedTo: `user:${orgId}:inspector001`,
      scheduledDate: daysAgo(-1),
      status: WorkOrderStatus.IN_PROGRESS,
      priority: 'HIGH',
      estimatedCost: 850000,
      mediaIds: [],
      timeline: [
        { timestamp: daysAgo(3), fromStatus: null, toStatus: WorkOrderStatus.OPEN, actorId: userId, notes: '작업지시 생성' },
        { timestamp: daysAgo(2), fromStatus: WorkOrderStatus.OPEN, toStatus: WorkOrderStatus.IN_PROGRESS, actorId: `user:${orgId}:inspector001`, notes: '현장 조치 시작' },
      ],
      createdAt: daysAgo(3),
      updatedAt: daysAgo(2),
      createdBy: userId,
      updatedBy: `user:${orgId}:inspector001`,
    },
    {
      _id: `workOrder:${orgId}:wo_seed_002`,
      docType: 'workOrder',
      orgId,
      complexId,
      complaintId: `complaint:${orgId}:cmp_seed_001`,
      title: '3층 화장실 배관 누수 긴급 수리',
      description: '누수 배관 교체 및 실링 처리. 임시 조치 후 공사 범위 확인.',
      assignedTo: `user:${orgId}:inspector001`,
      scheduledDate: daysAgo(0),
      status: WorkOrderStatus.OPEN,
      priority: 'URGENT',
      estimatedCost: 400000,
      vendor: '(주)한국배관공사',
      mediaIds: [],
      timeline: [
        { timestamp: daysAgo(1), fromStatus: null, toStatus: WorkOrderStatus.OPEN, actorId: userId, notes: '작업지시 생성' },
      ],
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
      createdBy: userId,
      updatedBy: userId,
    },
  ];

  return { complaints, workOrders };
}
